#!/usr/bin/env bash
#!/bin/bash

# Check if the correct number of parameters are passed
if [ $# -lt 4 ]; then
	  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	    exit 1
fi

# Get the file path, server IP, username, and SSH private key
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Disable strict host key checking
ssh-keygen -R "$SERVER_IP"

# Transfer  file to the user home directory
scp -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/""

