#!/usr/bin/env bash

# Install Nginx
sudo apt update && sudo apt install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/nginx.conf

# Create a default index.html file
sudo cat << EOF > /var/www/html/index.html
Hello World!
EOF

# Restart Nginx
sudo service nginx restart


