#!/usr/bin/env bash
#!/bin/bash

# Install Nginx
sudo apt-get install -y nginx

# Update Nginx configuration
sudo sed -i 's/listen 80 default_server;/listen 80;\n\t# Disable default server\nserver
{\n\tlisten 80;\n\troot /var/www/html;\n\tindex index.html;\n}/g' /etc/nginx/nginx.conf

# Create a test file
sudo echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
sudo service nginx restart

