#!/usr/bin/env bash

# Install Nginx
sudo apt update && sudo apt install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/nginx.conf

# Create a redirect configuration file
sudo cat << EOF > /etc/nginx/conf.d/redirect_me.conf
server {
    listen 80;
        server_name localhost;

	    location /redirect_me/ {
	            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
		        }
	}
EOF

# Reload Nginx
sudo service nginx reload
