#!/usr/bin/env bash
# Install HAproxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo tee -a /etc/haproxy/haproxy.cfg << EOF
frontend http-in
    bind *:80
    mode http
    option forwardfor header Connection
    option http-keep-alive      # enable keep-alive connections
    timeout http-keep-alive 65s # set  keep-alive timeout to 65 seconds
    default_backend servers     

backend servers
    mode http
    balance roundrobin
    server 362649-web-01 54.90.39.109 check port 80
    server 362649-web-02 3.94.213.245 check port 80
EOF

# Restart HAproxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy
